namespace WindowsApplication1
{
	// Token: 0x02000008 RID: 8
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x0600001E RID: 30 RVA: 0x00002BA8 File Offset: 0x00000FA8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600001F RID: 31
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.SN = new global::System.Windows.Forms.TextBox();
			this.KEY = new global::System.Windows.Forms.TextBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label50 = new global::System.Windows.Forms.Label();
			this.Label40 = new global::System.Windows.Forms.Label();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label49 = new global::System.Windows.Forms.Label();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label48 = new global::System.Windows.Forms.Label();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label54 = new global::System.Windows.Forms.Label();
			this.Label57 = new global::System.Windows.Forms.Label();
			this.Label47 = new global::System.Windows.Forms.Label();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label56 = new global::System.Windows.Forms.Label();
			this.Label46 = new global::System.Windows.Forms.Label();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label45 = new global::System.Windows.Forms.Label();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label44 = new global::System.Windows.Forms.Label();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label43 = new global::System.Windows.Forms.Label();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label53 = new global::System.Windows.Forms.Label();
			this.Label52 = new global::System.Windows.Forms.Label();
			this.Label42 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label51 = new global::System.Windows.Forms.Label();
			this.Label41 = new global::System.Windows.Forms.Label();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.WLBQTY = new global::System.Windows.Forms.TextBox();
			this.SCMQTY = new global::System.Windows.Forms.TextBox();
			this.PURQTY = new global::System.Windows.Forms.TextBox();
			this.INVQTY = new global::System.Windows.Forms.TextBox();
			this.CWBQTY = new global::System.Windows.Forms.TextBox();
			this.WLB = new global::System.Windows.Forms.CheckBox();
			this.SCM = new global::System.Windows.Forms.CheckBox();
			this.PUR = new global::System.Windows.Forms.CheckBox();
			this.INV = new global::System.Windows.Forms.CheckBox();
			this.CWB = new global::System.Windows.Forms.CheckBox();
			this.SYSQTY = new global::System.Windows.Forms.TextBox();
			this.RMAQTY = new global::System.Windows.Forms.TextBox();
			this.PJMQTY = new global::System.Windows.Forms.TextBox();
			this.GZSQTY = new global::System.Windows.Forms.TextBox();
			this.CRMQTY = new global::System.Windows.Forms.TextBox();
			this.SYS = new global::System.Windows.Forms.CheckBox();
			this.RMA = new global::System.Windows.Forms.CheckBox();
			this.PJM = new global::System.Windows.Forms.CheckBox();
			this.GZS = new global::System.Windows.Forms.CheckBox();
			this.ALLQTY = new global::System.Windows.Forms.TextBox();
			this.CRM = new global::System.Windows.Forms.CheckBox();
			this.ZCSQTY = new global::System.Windows.Forms.TextBox();
			this.SXMQTY = new global::System.Windows.Forms.TextBox();
			this.RGSQTY = new global::System.Windows.Forms.TextBox();
			this.KJSQTY = new global::System.Windows.Forms.TextBox();
			this.GYSQTY = new global::System.Windows.Forms.TextBox();
			this.ALL = new global::System.Windows.Forms.CheckBox();
			this.COPQTY = new global::System.Windows.Forms.TextBox();
			this.ZCS = new global::System.Windows.Forms.CheckBox();
			this.SXM = new global::System.Windows.Forms.CheckBox();
			this.RGS = new global::System.Windows.Forms.CheckBox();
			this.KJS = new global::System.Windows.Forms.CheckBox();
			this.GYS = new global::System.Windows.Forms.CheckBox();
			this.COP = new global::System.Windows.Forms.CheckBox();
			this.YSFQTY = new global::System.Windows.Forms.TextBox();
			this.YSF = new global::System.Windows.Forms.CheckBox();
			this.SGMQTY = new global::System.Windows.Forms.TextBox();
			this.SGM = new global::System.Windows.Forms.CheckBox();
			this.QMSQTY = new global::System.Windows.Forms.TextBox();
			this.QMS = new global::System.Windows.Forms.CheckBox();
			this.JCAQTY = new global::System.Windows.Forms.TextBox();
			this.JCA = new global::System.Windows.Forms.CheckBox();
			this.FIBQTY = new global::System.Windows.Forms.TextBox();
			this.FIB = new global::System.Windows.Forms.CheckBox();
			this.BASQTY = new global::System.Windows.Forms.TextBox();
			this.BAS = new global::System.Windows.Forms.CheckBox();
			this.REGSTR = new global::System.Windows.Forms.TextBox();
			this.Label61 = new global::System.Windows.Forms.Label();
			this.Label62 = new global::System.Windows.Forms.Label();
			this.PW = new global::System.Windows.Forms.TextBox();
			this.Label63 = new global::System.Windows.Forms.Label();
			this.Label64 = new global::System.Windows.Forms.Label();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.CCode = new global::System.Windows.Forms.TextBox();
			this.Label55 = new global::System.Windows.Forms.Label();
			this.GroupBox1.SuspendLayout();
			base.SuspendLayout();
			global::System.Windows.Forms.Control button = this.Button1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(523, 579);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(75, 23);
			button2.Size = size;
			this.Button1.TabIndex = 0;
			this.Button1.Text = "注册";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control sn = this.SN;
			location = new global::System.Drawing.Point(14, 24);
			sn.Location = location;
			this.SN.Name = "SN";
			global::System.Windows.Forms.Control sn2 = this.SN;
			size = new global::System.Drawing.Size(445, 21);
			sn2.Size = size;
			this.SN.TabIndex = 1;
			this.ToolTip1.SetToolTip(this.SN, "请输入安装代号Hacked！");
			global::System.Windows.Forms.Control key = this.KEY;
			location = new global::System.Drawing.Point(12, 538);
			key.Location = location;
			this.KEY.Multiline = true;
			this.KEY.Name = "KEY";
			this.KEY.ReadOnly = true;
			global::System.Windows.Forms.Control key2 = this.KEY;
			size = new global::System.Drawing.Size(458, 64);
			key2.Size = size;
			this.KEY.TabIndex = 1;
			this.GroupBox1.Controls.Add(this.Label50);
			this.GroupBox1.Controls.Add(this.Label40);
			this.GroupBox1.Controls.Add(this.Label30);
			this.GroupBox1.Controls.Add(this.Label20);
			this.GroupBox1.Controls.Add(this.Label10);
			this.GroupBox1.Controls.Add(this.Label49);
			this.GroupBox1.Controls.Add(this.Label39);
			this.GroupBox1.Controls.Add(this.Label29);
			this.GroupBox1.Controls.Add(this.Label19);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.Label48);
			this.GroupBox1.Controls.Add(this.Label38);
			this.GroupBox1.Controls.Add(this.Label28);
			this.GroupBox1.Controls.Add(this.Label18);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.Label54);
			this.GroupBox1.Controls.Add(this.Label57);
			this.GroupBox1.Controls.Add(this.Label47);
			this.GroupBox1.Controls.Add(this.Label37);
			this.GroupBox1.Controls.Add(this.Label27);
			this.GroupBox1.Controls.Add(this.Label17);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.Label56);
			this.GroupBox1.Controls.Add(this.Label46);
			this.GroupBox1.Controls.Add(this.Label36);
			this.GroupBox1.Controls.Add(this.Label26);
			this.GroupBox1.Controls.Add(this.Label16);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.Label45);
			this.GroupBox1.Controls.Add(this.Label35);
			this.GroupBox1.Controls.Add(this.Label25);
			this.GroupBox1.Controls.Add(this.Label15);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.Label44);
			this.GroupBox1.Controls.Add(this.Label34);
			this.GroupBox1.Controls.Add(this.Label24);
			this.GroupBox1.Controls.Add(this.Label14);
			this.GroupBox1.Controls.Add(this.Label7);
			this.GroupBox1.Controls.Add(this.Label43);
			this.GroupBox1.Controls.Add(this.Label33);
			this.GroupBox1.Controls.Add(this.Label23);
			this.GroupBox1.Controls.Add(this.Label13);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.Label53);
			this.GroupBox1.Controls.Add(this.Label52);
			this.GroupBox1.Controls.Add(this.Label42);
			this.GroupBox1.Controls.Add(this.Label32);
			this.GroupBox1.Controls.Add(this.Label22);
			this.GroupBox1.Controls.Add(this.Label12);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.Label51);
			this.GroupBox1.Controls.Add(this.Label41);
			this.GroupBox1.Controls.Add(this.Label31);
			this.GroupBox1.Controls.Add(this.Label21);
			this.GroupBox1.Controls.Add(this.Label11);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.WLBQTY);
			this.GroupBox1.Controls.Add(this.SCMQTY);
			this.GroupBox1.Controls.Add(this.PURQTY);
			this.GroupBox1.Controls.Add(this.INVQTY);
			this.GroupBox1.Controls.Add(this.CWBQTY);
			this.GroupBox1.Controls.Add(this.WLB);
			this.GroupBox1.Controls.Add(this.SCM);
			this.GroupBox1.Controls.Add(this.PUR);
			this.GroupBox1.Controls.Add(this.INV);
			this.GroupBox1.Controls.Add(this.CWB);
			this.GroupBox1.Controls.Add(this.SYSQTY);
			this.GroupBox1.Controls.Add(this.RMAQTY);
			this.GroupBox1.Controls.Add(this.PJMQTY);
			this.GroupBox1.Controls.Add(this.GZSQTY);
			this.GroupBox1.Controls.Add(this.CRMQTY);
			this.GroupBox1.Controls.Add(this.SYS);
			this.GroupBox1.Controls.Add(this.RMA);
			this.GroupBox1.Controls.Add(this.PJM);
			this.GroupBox1.Controls.Add(this.GZS);
			this.GroupBox1.Controls.Add(this.ALLQTY);
			this.GroupBox1.Controls.Add(this.CRM);
			this.GroupBox1.Controls.Add(this.ZCSQTY);
			this.GroupBox1.Controls.Add(this.SXMQTY);
			this.GroupBox1.Controls.Add(this.RGSQTY);
			this.GroupBox1.Controls.Add(this.KJSQTY);
			this.GroupBox1.Controls.Add(this.GYSQTY);
			this.GroupBox1.Controls.Add(this.ALL);
			this.GroupBox1.Controls.Add(this.COPQTY);
			this.GroupBox1.Controls.Add(this.ZCS);
			this.GroupBox1.Controls.Add(this.SXM);
			this.GroupBox1.Controls.Add(this.RGS);
			this.GroupBox1.Controls.Add(this.KJS);
			this.GroupBox1.Controls.Add(this.GYS);
			this.GroupBox1.Controls.Add(this.COP);
			this.GroupBox1.Controls.Add(this.YSFQTY);
			this.GroupBox1.Controls.Add(this.YSF);
			this.GroupBox1.Controls.Add(this.SGMQTY);
			this.GroupBox1.Controls.Add(this.SGM);
			this.GroupBox1.Controls.Add(this.QMSQTY);
			this.GroupBox1.Controls.Add(this.QMS);
			this.GroupBox1.Controls.Add(this.JCAQTY);
			this.GroupBox1.Controls.Add(this.JCA);
			this.GroupBox1.Controls.Add(this.FIBQTY);
			this.GroupBox1.Controls.Add(this.FIB);
			this.GroupBox1.Controls.Add(this.BASQTY);
			this.GroupBox1.Controls.Add(this.BAS);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(12, 62);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(619, 399);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 2;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "功能选择";
			this.ToolTip1.SetToolTip(this.GroupBox1, "选取要注册的功能！");
			this.Label50.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label50;
			location = new global::System.Drawing.Point(509, 270);
			label.Location = location;
			this.Label50.Name = "Label50";
			global::System.Windows.Forms.Control label2 = this.Label50;
			size = new global::System.Drawing.Size(29, 12);
			label2.Size = size;
			this.Label50.TabIndex = 2;
			this.Label50.Text = "功能";
			this.Label40.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label40;
			location = new global::System.Drawing.Point(509, 213);
			label3.Location = location;
			this.Label40.Name = "Label40";
			global::System.Windows.Forms.Control label4 = this.Label40;
			size = new global::System.Drawing.Size(29, 12);
			label4.Size = size;
			this.Label40.TabIndex = 2;
			this.Label40.Text = "功能";
			this.Label30.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label30;
			location = new global::System.Drawing.Point(509, 152);
			label5.Location = location;
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control label6 = this.Label30;
			size = new global::System.Drawing.Size(29, 12);
			label6.Size = size;
			this.Label30.TabIndex = 2;
			this.Label30.Text = "功能";
			this.Label20.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label20;
			location = new global::System.Drawing.Point(509, 94);
			label7.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control label8 = this.Label20;
			size = new global::System.Drawing.Size(29, 12);
			label8.Size = size;
			this.Label20.TabIndex = 2;
			this.Label20.Text = "功能";
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label10;
			location = new global::System.Drawing.Point(509, 39);
			label9.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label10 = this.Label10;
			size = new global::System.Drawing.Size(29, 12);
			label10.Size = size;
			this.Label10.TabIndex = 2;
			this.Label10.Text = "功能";
			this.Label49.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label49;
			location = new global::System.Drawing.Point(509, 270);
			label11.Location = location;
			this.Label49.Name = "Label49";
			global::System.Windows.Forms.Control label12 = this.Label49;
			size = new global::System.Drawing.Size(29, 12);
			label12.Size = size;
			this.Label49.TabIndex = 2;
			this.Label49.Text = "功能";
			this.Label39.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label39;
			location = new global::System.Drawing.Point(509, 213);
			label13.Location = location;
			this.Label39.Name = "Label39";
			global::System.Windows.Forms.Control label14 = this.Label39;
			size = new global::System.Drawing.Size(29, 12);
			label14.Size = size;
			this.Label39.TabIndex = 2;
			this.Label39.Text = "功能";
			this.Label29.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label29;
			location = new global::System.Drawing.Point(509, 152);
			label15.Location = location;
			this.Label29.Name = "Label29";
			global::System.Windows.Forms.Control label16 = this.Label29;
			size = new global::System.Drawing.Size(29, 12);
			label16.Size = size;
			this.Label29.TabIndex = 2;
			this.Label29.Text = "功能";
			this.Label19.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label19;
			location = new global::System.Drawing.Point(509, 94);
			label17.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control label18 = this.Label19;
			size = new global::System.Drawing.Size(29, 12);
			label18.Size = size;
			this.Label19.TabIndex = 2;
			this.Label19.Text = "功能";
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label19 = this.Label8;
			location = new global::System.Drawing.Point(509, 39);
			label19.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label20 = this.Label8;
			size = new global::System.Drawing.Size(29, 12);
			label20.Size = size;
			this.Label8.TabIndex = 2;
			this.Label8.Text = "功能";
			this.Label48.AutoSize = true;
			global::System.Windows.Forms.Control label21 = this.Label48;
			location = new global::System.Drawing.Point(362, 270);
			label21.Location = location;
			this.Label48.Name = "Label48";
			global::System.Windows.Forms.Control label22 = this.Label48;
			size = new global::System.Drawing.Size(29, 12);
			label22.Size = size;
			this.Label48.TabIndex = 2;
			this.Label48.Text = "功能";
			this.Label38.AutoSize = true;
			global::System.Windows.Forms.Control label23 = this.Label38;
			location = new global::System.Drawing.Point(362, 213);
			label23.Location = location;
			this.Label38.Name = "Label38";
			global::System.Windows.Forms.Control label24 = this.Label38;
			size = new global::System.Drawing.Size(29, 12);
			label24.Size = size;
			this.Label38.TabIndex = 2;
			this.Label38.Text = "功能";
			this.Label28.AutoSize = true;
			global::System.Windows.Forms.Control label25 = this.Label28;
			location = new global::System.Drawing.Point(362, 152);
			label25.Location = location;
			this.Label28.Name = "Label28";
			global::System.Windows.Forms.Control label26 = this.Label28;
			size = new global::System.Drawing.Size(29, 12);
			label26.Size = size;
			this.Label28.TabIndex = 2;
			this.Label28.Text = "功能";
			this.Label18.AutoSize = true;
			global::System.Windows.Forms.Control label27 = this.Label18;
			location = new global::System.Drawing.Point(362, 94);
			label27.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control label28 = this.Label18;
			size = new global::System.Drawing.Size(29, 12);
			label28.Size = size;
			this.Label18.TabIndex = 2;
			this.Label18.Text = "功能";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label6;
			location = new global::System.Drawing.Point(362, 39);
			label29.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label30 = this.Label6;
			size = new global::System.Drawing.Size(29, 12);
			label30.Size = size;
			this.Label6.TabIndex = 2;
			this.Label6.Text = "功能";
			this.Label54.AutoSize = true;
			global::System.Windows.Forms.Control label31 = this.Label54;
			location = new global::System.Drawing.Point(360, 334);
			label31.Location = location;
			this.Label54.Name = "Label54";
			global::System.Windows.Forms.Control label32 = this.Label54;
			size = new global::System.Drawing.Size(29, 12);
			label32.Size = size;
			this.Label54.TabIndex = 2;
			this.Label54.Text = "功能";
			this.Label57.AutoSize = true;
			global::System.Windows.Forms.Control label33 = this.Label57;
			location = new global::System.Drawing.Point(216, 334);
			label33.Location = location;
			this.Label57.Name = "Label57";
			global::System.Windows.Forms.Control label34 = this.Label57;
			size = new global::System.Drawing.Size(29, 12);
			label34.Size = size;
			this.Label57.TabIndex = 2;
			this.Label57.Text = "功能";
			this.Label47.AutoSize = true;
			global::System.Windows.Forms.Control label35 = this.Label47;
			location = new global::System.Drawing.Point(216, 270);
			label35.Location = location;
			this.Label47.Name = "Label47";
			global::System.Windows.Forms.Control label36 = this.Label47;
			size = new global::System.Drawing.Size(29, 12);
			label36.Size = size;
			this.Label47.TabIndex = 2;
			this.Label47.Text = "功能";
			this.Label37.AutoSize = true;
			global::System.Windows.Forms.Control label37 = this.Label37;
			location = new global::System.Drawing.Point(216, 213);
			label37.Location = location;
			this.Label37.Name = "Label37";
			global::System.Windows.Forms.Control label38 = this.Label37;
			size = new global::System.Drawing.Size(29, 12);
			label38.Size = size;
			this.Label37.TabIndex = 2;
			this.Label37.Text = "功能";
			this.Label27.AutoSize = true;
			global::System.Windows.Forms.Control label39 = this.Label27;
			location = new global::System.Drawing.Point(216, 152);
			label39.Location = location;
			this.Label27.Name = "Label27";
			global::System.Windows.Forms.Control label40 = this.Label27;
			size = new global::System.Drawing.Size(29, 12);
			label40.Size = size;
			this.Label27.TabIndex = 2;
			this.Label27.Text = "功能";
			this.Label17.AutoSize = true;
			global::System.Windows.Forms.Control label41 = this.Label17;
			location = new global::System.Drawing.Point(216, 94);
			label41.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label42 = this.Label17;
			size = new global::System.Drawing.Size(29, 12);
			label42.Size = size;
			this.Label17.TabIndex = 2;
			this.Label17.Text = "功能";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label43 = this.Label4;
			location = new global::System.Drawing.Point(231, 39);
			label43.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label44 = this.Label4;
			size = new global::System.Drawing.Size(29, 12);
			label44.Size = size;
			this.Label4.TabIndex = 2;
			this.Label4.Text = "功能";
			this.Label56.AutoSize = true;
			global::System.Windows.Forms.Control label45 = this.Label56;
			location = new global::System.Drawing.Point(68, 330);
			label45.Location = location;
			this.Label56.Name = "Label56";
			global::System.Windows.Forms.Control label46 = this.Label56;
			size = new global::System.Drawing.Size(29, 12);
			label46.Size = size;
			this.Label56.TabIndex = 2;
			this.Label56.Text = "功能";
			this.Label46.AutoSize = true;
			global::System.Windows.Forms.Control label47 = this.Label46;
			location = new global::System.Drawing.Point(68, 266);
			label47.Location = location;
			this.Label46.Name = "Label46";
			global::System.Windows.Forms.Control label48 = this.Label46;
			size = new global::System.Drawing.Size(29, 12);
			label48.Size = size;
			this.Label46.TabIndex = 2;
			this.Label46.Text = "功能";
			this.Label36.AutoSize = true;
			global::System.Windows.Forms.Control label49 = this.Label36;
			location = new global::System.Drawing.Point(68, 209);
			label49.Location = location;
			this.Label36.Name = "Label36";
			global::System.Windows.Forms.Control label50 = this.Label36;
			size = new global::System.Drawing.Size(29, 12);
			label50.Size = size;
			this.Label36.TabIndex = 2;
			this.Label36.Text = "功能";
			this.Label26.AutoSize = true;
			global::System.Windows.Forms.Control label51 = this.Label26;
			location = new global::System.Drawing.Point(68, 148);
			label51.Location = location;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label52 = this.Label26;
			size = new global::System.Drawing.Size(29, 12);
			label52.Size = size;
			this.Label26.TabIndex = 2;
			this.Label26.Text = "功能";
			this.Label16.AutoSize = true;
			global::System.Windows.Forms.Control label53 = this.Label16;
			location = new global::System.Drawing.Point(68, 90);
			label53.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label54 = this.Label16;
			size = new global::System.Drawing.Size(29, 12);
			label54.Size = size;
			this.Label16.TabIndex = 2;
			this.Label16.Text = "功能";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label55 = this.Label2;
			location = new global::System.Drawing.Point(68, 35);
			label55.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label56 = this.Label2;
			size = new global::System.Drawing.Size(53, 12);
			label56.Size = size;
			this.Label2.TabIndex = 2;
			this.Label2.Text = "功能代号";
			this.Label45.AutoSize = true;
			global::System.Windows.Forms.Control label57 = this.Label45;
			location = new global::System.Drawing.Point(464, 270);
			label57.Location = location;
			this.Label45.Name = "Label45";
			global::System.Windows.Forms.Control label58 = this.Label45;
			size = new global::System.Drawing.Size(41, 12);
			label58.Size = size;
			this.Label45.TabIndex = 2;
			this.Label45.Text = "用户数";
			this.Label35.AutoSize = true;
			global::System.Windows.Forms.Control label59 = this.Label35;
			location = new global::System.Drawing.Point(464, 213);
			label59.Location = location;
			this.Label35.Name = "Label35";
			global::System.Windows.Forms.Control label60 = this.Label35;
			size = new global::System.Drawing.Size(41, 12);
			label60.Size = size;
			this.Label35.TabIndex = 2;
			this.Label35.Text = "用户数";
			this.Label25.AutoSize = true;
			global::System.Windows.Forms.Control label61 = this.Label25;
			location = new global::System.Drawing.Point(464, 152);
			label61.Location = location;
			this.Label25.Name = "Label25";
			global::System.Windows.Forms.Control label62 = this.Label25;
			size = new global::System.Drawing.Size(41, 12);
			label62.Size = size;
			this.Label25.TabIndex = 2;
			this.Label25.Text = "用户数";
			this.Label15.AutoSize = true;
			global::System.Windows.Forms.Control label63 = this.Label15;
			location = new global::System.Drawing.Point(464, 94);
			label63.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label64 = this.Label15;
			size = new global::System.Drawing.Size(41, 12);
			label64.Size = size;
			this.Label15.TabIndex = 2;
			this.Label15.Text = "用户数";
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label65 = this.Label9;
			location = new global::System.Drawing.Point(464, 39);
			label65.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label66 = this.Label9;
			size = new global::System.Drawing.Size(41, 12);
			label66.Size = size;
			this.Label9.TabIndex = 2;
			this.Label9.Text = "用户数";
			this.Label44.AutoSize = true;
			global::System.Windows.Forms.Control label67 = this.Label44;
			location = new global::System.Drawing.Point(464, 270);
			label67.Location = location;
			this.Label44.Name = "Label44";
			global::System.Windows.Forms.Control label68 = this.Label44;
			size = new global::System.Drawing.Size(41, 12);
			label68.Size = size;
			this.Label44.TabIndex = 2;
			this.Label44.Text = "用户数";
			this.Label34.AutoSize = true;
			global::System.Windows.Forms.Control label69 = this.Label34;
			location = new global::System.Drawing.Point(464, 213);
			label69.Location = location;
			this.Label34.Name = "Label34";
			global::System.Windows.Forms.Control label70 = this.Label34;
			size = new global::System.Drawing.Size(41, 12);
			label70.Size = size;
			this.Label34.TabIndex = 2;
			this.Label34.Text = "用户数";
			this.Label24.AutoSize = true;
			global::System.Windows.Forms.Control label71 = this.Label24;
			location = new global::System.Drawing.Point(464, 152);
			label71.Location = location;
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control label72 = this.Label24;
			size = new global::System.Drawing.Size(41, 12);
			label72.Size = size;
			this.Label24.TabIndex = 2;
			this.Label24.Text = "用户数";
			this.Label14.AutoSize = true;
			global::System.Windows.Forms.Control label73 = this.Label14;
			location = new global::System.Drawing.Point(464, 94);
			label73.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label74 = this.Label14;
			size = new global::System.Drawing.Size(41, 12);
			label74.Size = size;
			this.Label14.TabIndex = 2;
			this.Label14.Text = "用户数";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label75 = this.Label7;
			location = new global::System.Drawing.Point(464, 39);
			label75.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label76 = this.Label7;
			size = new global::System.Drawing.Size(41, 12);
			label76.Size = size;
			this.Label7.TabIndex = 2;
			this.Label7.Text = "用户数";
			this.Label43.AutoSize = true;
			global::System.Windows.Forms.Control label77 = this.Label43;
			location = new global::System.Drawing.Point(317, 270);
			label77.Location = location;
			this.Label43.Name = "Label43";
			global::System.Windows.Forms.Control label78 = this.Label43;
			size = new global::System.Drawing.Size(41, 12);
			label78.Size = size;
			this.Label43.TabIndex = 2;
			this.Label43.Text = "用户数";
			this.Label33.AutoSize = true;
			global::System.Windows.Forms.Control label79 = this.Label33;
			location = new global::System.Drawing.Point(317, 213);
			label79.Location = location;
			this.Label33.Name = "Label33";
			global::System.Windows.Forms.Control label80 = this.Label33;
			size = new global::System.Drawing.Size(41, 12);
			label80.Size = size;
			this.Label33.TabIndex = 2;
			this.Label33.Text = "用户数";
			this.Label23.AutoSize = true;
			global::System.Windows.Forms.Control label81 = this.Label23;
			location = new global::System.Drawing.Point(317, 152);
			label81.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control label82 = this.Label23;
			size = new global::System.Drawing.Size(41, 12);
			label82.Size = size;
			this.Label23.TabIndex = 2;
			this.Label23.Text = "用户数";
			this.Label13.AutoSize = true;
			global::System.Windows.Forms.Control label83 = this.Label13;
			location = new global::System.Drawing.Point(317, 94);
			label83.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label84 = this.Label13;
			size = new global::System.Drawing.Size(41, 12);
			label84.Size = size;
			this.Label13.TabIndex = 2;
			this.Label13.Text = "用户数";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label85 = this.Label5;
			location = new global::System.Drawing.Point(317, 39);
			label85.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label86 = this.Label5;
			size = new global::System.Drawing.Size(41, 12);
			label86.Size = size;
			this.Label5.TabIndex = 2;
			this.Label5.Text = "用户数";
			this.Label53.AutoSize = true;
			global::System.Windows.Forms.Control label87 = this.Label53;
			location = new global::System.Drawing.Point(315, 334);
			label87.Location = location;
			this.Label53.Name = "Label53";
			global::System.Windows.Forms.Control label88 = this.Label53;
			size = new global::System.Drawing.Size(41, 12);
			label88.Size = size;
			this.Label53.TabIndex = 2;
			this.Label53.Text = "用户数";
			this.Label52.AutoSize = true;
			global::System.Windows.Forms.Control label89 = this.Label52;
			location = new global::System.Drawing.Point(170, 334);
			label89.Location = location;
			this.Label52.Name = "Label52";
			global::System.Windows.Forms.Control label90 = this.Label52;
			size = new global::System.Drawing.Size(41, 12);
			label90.Size = size;
			this.Label52.TabIndex = 2;
			this.Label52.Text = "用户数";
			this.Label42.AutoSize = true;
			global::System.Windows.Forms.Control label91 = this.Label42;
			location = new global::System.Drawing.Point(170, 270);
			label91.Location = location;
			this.Label42.Name = "Label42";
			global::System.Windows.Forms.Control label92 = this.Label42;
			size = new global::System.Drawing.Size(41, 12);
			label92.Size = size;
			this.Label42.TabIndex = 2;
			this.Label42.Text = "用户数";
			this.Label32.AutoSize = true;
			global::System.Windows.Forms.Control label93 = this.Label32;
			location = new global::System.Drawing.Point(170, 213);
			label93.Location = location;
			this.Label32.Name = "Label32";
			global::System.Windows.Forms.Control label94 = this.Label32;
			size = new global::System.Drawing.Size(41, 12);
			label94.Size = size;
			this.Label32.TabIndex = 2;
			this.Label32.Text = "用户数";
			this.Label22.AutoSize = true;
			global::System.Windows.Forms.Control label95 = this.Label22;
			location = new global::System.Drawing.Point(170, 152);
			label95.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control label96 = this.Label22;
			size = new global::System.Drawing.Size(41, 12);
			label96.Size = size;
			this.Label22.TabIndex = 2;
			this.Label22.Text = "用户数";
			this.Label12.AutoSize = true;
			global::System.Windows.Forms.Control label97 = this.Label12;
			location = new global::System.Drawing.Point(170, 94);
			label97.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label98 = this.Label12;
			size = new global::System.Drawing.Size(41, 12);
			label98.Size = size;
			this.Label12.TabIndex = 2;
			this.Label12.Text = "用户数";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label99 = this.Label3;
			location = new global::System.Drawing.Point(170, 39);
			label99.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label100 = this.Label3;
			size = new global::System.Drawing.Size(41, 12);
			label100.Size = size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "用户数";
			this.Label51.AutoSize = true;
			global::System.Windows.Forms.Control label101 = this.Label51;
			location = new global::System.Drawing.Point(23, 332);
			label101.Location = location;
			this.Label51.Name = "Label51";
			global::System.Windows.Forms.Control label102 = this.Label51;
			size = new global::System.Drawing.Size(41, 12);
			label102.Size = size;
			this.Label51.TabIndex = 2;
			this.Label51.Text = "用户数";
			this.Label41.AutoSize = true;
			global::System.Windows.Forms.Control label103 = this.Label41;
			location = new global::System.Drawing.Point(23, 268);
			label103.Location = location;
			this.Label41.Name = "Label41";
			global::System.Windows.Forms.Control label104 = this.Label41;
			size = new global::System.Drawing.Size(41, 12);
			label104.Size = size;
			this.Label41.TabIndex = 2;
			this.Label41.Text = "用户数";
			this.Label31.AutoSize = true;
			global::System.Windows.Forms.Control label105 = this.Label31;
			location = new global::System.Drawing.Point(23, 211);
			label105.Location = location;
			this.Label31.Name = "Label31";
			global::System.Windows.Forms.Control label106 = this.Label31;
			size = new global::System.Drawing.Size(41, 12);
			label106.Size = size;
			this.Label31.TabIndex = 2;
			this.Label31.Text = "用户数";
			this.Label21.AutoSize = true;
			global::System.Windows.Forms.Control label107 = this.Label21;
			location = new global::System.Drawing.Point(23, 150);
			label107.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control label108 = this.Label21;
			size = new global::System.Drawing.Size(41, 12);
			label108.Size = size;
			this.Label21.TabIndex = 2;
			this.Label21.Text = "用户数";
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label109 = this.Label11;
			location = new global::System.Drawing.Point(23, 92);
			label109.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label110 = this.Label11;
			size = new global::System.Drawing.Size(41, 12);
			label110.Size = size;
			this.Label11.TabIndex = 2;
			this.Label11.Text = "用户数";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label111 = this.Label1;
			location = new global::System.Drawing.Point(23, 37);
			label111.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label112 = this.Label1;
			size = new global::System.Drawing.Size(41, 12);
			label112.Size = size;
			this.Label1.TabIndex = 2;
			this.Label1.Text = "用户数";
			this.WLBQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "WLBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.WLBQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.WLBQTY;
			global::System.Windows.Forms.Control wlbqty = this.WLBQTY;
			location = new global::System.Drawing.Point(464, 288);
			wlbqty.Location = location;
			this.WLBQTY.MaxLength = 2;
			this.WLBQTY.Name = "WLBQTY";
			global::System.Windows.Forms.Control wlbqty2 = this.WLBQTY;
			size = new global::System.Drawing.Size(41, 21);
			wlbqty2.Size = size;
			this.WLBQTY.TabIndex = 1;
			this.SCMQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "SCMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.SCMQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.SCMQTY;
			global::System.Windows.Forms.Control scmqty = this.SCMQTY;
			location = new global::System.Drawing.Point(464, 231);
			scmqty.Location = location;
			this.SCMQTY.MaxLength = 2;
			this.SCMQTY.Name = "SCMQTY";
			global::System.Windows.Forms.Control scmqty2 = this.SCMQTY;
			size = new global::System.Drawing.Size(41, 21);
			scmqty2.Size = size;
			this.SCMQTY.TabIndex = 1;
			this.PURQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "PURQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.PURQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.PURQTY;
			global::System.Windows.Forms.Control purqty = this.PURQTY;
			location = new global::System.Drawing.Point(464, 170);
			purqty.Location = location;
			this.PURQTY.MaxLength = 2;
			this.PURQTY.Name = "PURQTY";
			global::System.Windows.Forms.Control purqty2 = this.PURQTY;
			size = new global::System.Drawing.Size(41, 21);
			purqty2.Size = size;
			this.PURQTY.TabIndex = 1;
			this.INVQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "INVQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.INVQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.INVQTY;
			global::System.Windows.Forms.Control invqty = this.INVQTY;
			location = new global::System.Drawing.Point(464, 112);
			invqty.Location = location;
			this.INVQTY.MaxLength = 2;
			this.INVQTY.Name = "INVQTY";
			global::System.Windows.Forms.Control invqty2 = this.INVQTY;
			size = new global::System.Drawing.Size(41, 21);
			invqty2.Size = size;
			this.INVQTY.TabIndex = 1;
			this.CWBQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "CWBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.CWBQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.CWBQTY;
			global::System.Windows.Forms.Control cwbqty = this.CWBQTY;
			location = new global::System.Drawing.Point(464, 57);
			cwbqty.Location = location;
			this.CWBQTY.MaxLength = 2;
			this.CWBQTY.Name = "CWBQTY";
			global::System.Windows.Forms.Control cwbqty2 = this.CWBQTY;
			size = new global::System.Drawing.Size(41, 21);
			cwbqty2.Size = size;
			this.CWBQTY.TabIndex = 1;
			this.WLB.AutoSize = true;
			this.WLB.Checked = global::WindowsApplication1.My.MySettings.Default.WLBQTY;
			this.WLB.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "WLBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control wlb = this.WLB;
			location = new global::System.Drawing.Point(511, 290);
			wlb.Location = location;
			this.WLB.Name = "WLB";
			global::System.Windows.Forms.Control wlb2 = this.WLB;
			size = new global::System.Drawing.Size(60, 16);
			wlb2.Size = size;
			this.WLB.TabIndex = 0;
			this.WLB.Text = "物流包";
			this.ToolTip1.SetToolTip(this.WLB, "WLB 物流包(销售/采购/存货)");
			this.WLB.UseVisualStyleBackColor = true;
			this.SCM.AutoSize = true;
			this.SCM.Checked = global::WindowsApplication1.My.MySettings.Default.SCMQTY;
			this.SCM.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "SCMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control scm = this.SCM;
			location = new global::System.Drawing.Point(511, 233);
			scm.Location = location;
			this.SCM.Name = "SCM";
			global::System.Windows.Forms.Control scm2 = this.SCM;
			size = new global::System.Drawing.Size(72, 16);
			scm2.Size = size;
			this.SCM.TabIndex = 0;
			this.SCM.Text = "生产成本";
			this.ToolTip1.SetToolTip(this.SCM, "SCM 生产成本");
			this.SCM.UseVisualStyleBackColor = true;
			this.PUR.AutoSize = true;
			this.PUR.Checked = global::WindowsApplication1.My.MySettings.Default.PURQTY;
			this.PUR.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "PURQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control pur = this.PUR;
			location = new global::System.Drawing.Point(511, 172);
			pur.Location = location;
			this.PUR.Name = "PUR";
			global::System.Windows.Forms.Control pur2 = this.PUR;
			size = new global::System.Drawing.Size(48, 16);
			pur2.Size = size;
			this.PUR.TabIndex = 0;
			this.PUR.Text = "采购";
			this.ToolTip1.SetToolTip(this.PUR, "PUR 采购");
			this.PUR.UseVisualStyleBackColor = true;
			this.INV.AutoSize = true;
			this.INV.Checked = global::WindowsApplication1.My.MySettings.Default.INVQTY;
			this.INV.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "INVQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control inv = this.INV;
			location = new global::System.Drawing.Point(511, 114);
			inv.Location = location;
			this.INV.Name = "INV";
			global::System.Windows.Forms.Control inv2 = this.INV;
			size = new global::System.Drawing.Size(48, 16);
			inv2.Size = size;
			this.INV.TabIndex = 0;
			this.INV.Text = "存货";
			this.ToolTip1.SetToolTip(this.INV, "INV 存货");
			this.INV.UseVisualStyleBackColor = true;
			this.CWB.AutoSize = true;
			this.CWB.Checked = global::WindowsApplication1.My.MySettings.Default.CWBQTY;
			this.CWB.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "CWBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control cwb = this.CWB;
			location = new global::System.Drawing.Point(511, 59);
			cwb.Location = location;
			this.CWB.Name = "CWB";
			global::System.Windows.Forms.Control cwb2 = this.CWB;
			size = new global::System.Drawing.Size(96, 16);
			cwb2.Size = size;
			this.CWB.TabIndex = 0;
			this.CWB.Text = "财务报表平台";
			this.ToolTip1.SetToolTip(this.CWB, "CWB 财务报表平台");
			this.CWB.UseVisualStyleBackColor = true;
			this.SYSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "SYSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.SYSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.SYSQTY;
			global::System.Windows.Forms.Control sysqty = this.SYSQTY;
			location = new global::System.Drawing.Point(317, 288);
			sysqty.Location = location;
			this.SYSQTY.MaxLength = 2;
			this.SYSQTY.Name = "SYSQTY";
			global::System.Windows.Forms.Control sysqty2 = this.SYSQTY;
			size = new global::System.Drawing.Size(41, 21);
			sysqty2.Size = size;
			this.SYSQTY.TabIndex = 1;
			this.RMAQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "RMAQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.RMAQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.RMAQTY;
			global::System.Windows.Forms.Control rmaqty = this.RMAQTY;
			location = new global::System.Drawing.Point(317, 231);
			rmaqty.Location = location;
			this.RMAQTY.MaxLength = 2;
			this.RMAQTY.Name = "RMAQTY";
			global::System.Windows.Forms.Control rmaqty2 = this.RMAQTY;
			size = new global::System.Drawing.Size(41, 21);
			rmaqty2.Size = size;
			this.RMAQTY.TabIndex = 1;
			this.PJMQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "PJMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.PJMQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.PJMQTY;
			global::System.Windows.Forms.Control pjmqty = this.PJMQTY;
			location = new global::System.Drawing.Point(317, 170);
			pjmqty.Location = location;
			this.PJMQTY.MaxLength = 2;
			this.PJMQTY.Name = "PJMQTY";
			global::System.Windows.Forms.Control pjmqty2 = this.PJMQTY;
			size = new global::System.Drawing.Size(41, 21);
			pjmqty2.Size = size;
			this.PJMQTY.TabIndex = 1;
			this.GZSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "GZSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.GZSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.GZSQTY;
			global::System.Windows.Forms.Control gzsqty = this.GZSQTY;
			location = new global::System.Drawing.Point(317, 112);
			gzsqty.Location = location;
			this.GZSQTY.MaxLength = 2;
			this.GZSQTY.Name = "GZSQTY";
			global::System.Windows.Forms.Control gzsqty2 = this.GZSQTY;
			size = new global::System.Drawing.Size(41, 21);
			gzsqty2.Size = size;
			this.GZSQTY.TabIndex = 1;
			this.CRMQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "CRMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.CRMQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.CRMQTY;
			global::System.Windows.Forms.Control crmqty = this.CRMQTY;
			location = new global::System.Drawing.Point(317, 57);
			crmqty.Location = location;
			this.CRMQTY.MaxLength = 2;
			this.CRMQTY.Name = "CRMQTY";
			global::System.Windows.Forms.Control crmqty2 = this.CRMQTY;
			size = new global::System.Drawing.Size(41, 21);
			crmqty2.Size = size;
			this.CRMQTY.TabIndex = 1;
			this.SYS.AutoSize = true;
			this.SYS.Checked = global::WindowsApplication1.My.MySettings.Default.SYSQTY;
			this.SYS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "SYSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control sys = this.SYS;
			location = new global::System.Drawing.Point(364, 290);
			sys.Location = location;
			this.SYS.Name = "SYS";
			global::System.Windows.Forms.Control sys2 = this.SYS;
			size = new global::System.Drawing.Size(60, 16);
			sys2.Size = size;
			this.SYS.TabIndex = 0;
			this.SYS.Text = "系统包";
			this.ToolTip1.SetToolTip(this.SYS, "SYS 系统包（销售/采购/存货/生管/物料需求/应收应付/报表生成）");
			this.SYS.UseVisualStyleBackColor = true;
			this.RMA.AutoSize = true;
			this.RMA.Checked = global::WindowsApplication1.My.MySettings.Default.RMAQTY;
			this.RMA.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "RMAQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control rma = this.RMA;
			location = new global::System.Drawing.Point(364, 233);
			rma.Location = location;
			this.RMA.Name = "RMA";
			global::System.Windows.Forms.Control rma2 = this.RMA;
			size = new global::System.Drawing.Size(72, 16);
			rma2.Size = size;
			this.RMA.TabIndex = 0;
			this.RMA.Text = "服务管理";
			this.ToolTip1.SetToolTip(this.RMA, "RMA 服务管理");
			this.RMA.UseVisualStyleBackColor = true;
			this.PJM.AutoSize = true;
			this.PJM.Checked = global::WindowsApplication1.My.MySettings.Default.PJMQTY;
			this.PJM.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "PJMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control pjm = this.PJM;
			location = new global::System.Drawing.Point(364, 172);
			pjm.Location = location;
			this.PJM.Name = "PJM";
			global::System.Windows.Forms.Control pjm2 = this.PJM;
			size = new global::System.Drawing.Size(72, 16);
			pjm2.Size = size;
			this.PJM.TabIndex = 0;
			this.PJM.Text = "票据资金";
			this.ToolTip1.SetToolTip(this.PJM, "PJM 票据资金");
			this.PJM.UseVisualStyleBackColor = true;
			this.GZS.AutoSize = true;
			this.GZS.Checked = global::WindowsApplication1.My.MySettings.Default.GZSQTY;
			this.GZS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "GZSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control gzs = this.GZS;
			location = new global::System.Drawing.Point(364, 114);
			gzs.Location = location;
			this.GZS.Name = "GZS";
			global::System.Windows.Forms.Control gzs2 = this.GZS;
			size = new global::System.Drawing.Size(48, 16);
			gzs2.Size = size;
			this.GZS.TabIndex = 0;
			this.GZS.Text = "工资";
			this.ToolTip1.SetToolTip(this.GZS, "GZS 工资");
			this.GZS.UseVisualStyleBackColor = true;
			this.ALLQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "ALLQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.ALLQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.ALLQTY;
			global::System.Windows.Forms.Control allqty = this.ALLQTY;
			location = new global::System.Drawing.Point(315, 352);
			allqty.Location = location;
			this.ALLQTY.Name = "ALLQTY";
			global::System.Windows.Forms.Control allqty2 = this.ALLQTY;
			size = new global::System.Drawing.Size(41, 21);
			allqty2.Size = size;
			this.ALLQTY.TabIndex = 1;
			this.CRM.AutoSize = true;
			this.CRM.Checked = global::WindowsApplication1.My.MySettings.Default.CRMQTY;
			this.CRM.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "CRMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control crm = this.CRM;
			location = new global::System.Drawing.Point(364, 59);
			crm.Location = location;
			this.CRM.Name = "CRM";
			global::System.Windows.Forms.Control crm2 = this.CRM;
			size = new global::System.Drawing.Size(72, 16);
			crm2.Size = size;
			this.CRM.TabIndex = 0;
			this.CRM.Text = "客户关系";
			this.ToolTip1.SetToolTip(this.CRM, "CRM 客户关系");
			this.CRM.UseVisualStyleBackColor = true;
			this.ZCSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "ZCSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.ZCSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.ZCSQTY;
			global::System.Windows.Forms.Control zcsqty = this.ZCSQTY;
			location = new global::System.Drawing.Point(170, 352);
			zcsqty.Location = location;
			this.ZCSQTY.MaxLength = 2;
			this.ZCSQTY.Name = "ZCSQTY";
			global::System.Windows.Forms.Control zcsqty2 = this.ZCSQTY;
			size = new global::System.Drawing.Size(41, 21);
			zcsqty2.Size = size;
			this.ZCSQTY.TabIndex = 1;
			this.SXMQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "SXMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.SXMQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.SXMQTY;
			global::System.Windows.Forms.Control sxmqty = this.SXMQTY;
			location = new global::System.Drawing.Point(170, 288);
			sxmqty.Location = location;
			this.SXMQTY.MaxLength = 2;
			this.SXMQTY.Name = "SXMQTY";
			global::System.Windows.Forms.Control sxmqty2 = this.SXMQTY;
			size = new global::System.Drawing.Size(41, 21);
			sxmqty2.Size = size;
			this.SXMQTY.TabIndex = 1;
			this.RGSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "RGSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.RGSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.RGSQTY;
			global::System.Windows.Forms.Control rgsqty = this.RGSQTY;
			location = new global::System.Drawing.Point(170, 231);
			rgsqty.Location = location;
			this.RGSQTY.MaxLength = 2;
			this.RGSQTY.Name = "RGSQTY";
			global::System.Windows.Forms.Control rgsqty2 = this.RGSQTY;
			size = new global::System.Drawing.Size(41, 21);
			rgsqty2.Size = size;
			this.RGSQTY.TabIndex = 1;
			this.KJSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "KJSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.KJSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.KJSQTY;
			global::System.Windows.Forms.Control kjsqty = this.KJSQTY;
			location = new global::System.Drawing.Point(170, 170);
			kjsqty.Location = location;
			this.KJSQTY.MaxLength = 2;
			this.KJSQTY.Name = "KJSQTY";
			global::System.Windows.Forms.Control kjsqty2 = this.KJSQTY;
			size = new global::System.Drawing.Size(41, 21);
			kjsqty2.Size = size;
			this.KJSQTY.TabIndex = 1;
			this.GYSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "GYSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.GYSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.GYSQTY;
			global::System.Windows.Forms.Control gysqty = this.GYSQTY;
			location = new global::System.Drawing.Point(170, 112);
			gysqty.Location = location;
			this.GYSQTY.MaxLength = 2;
			this.GYSQTY.Name = "GYSQTY";
			global::System.Windows.Forms.Control gysqty2 = this.GYSQTY;
			size = new global::System.Drawing.Size(41, 21);
			gysqty2.Size = size;
			this.GYSQTY.TabIndex = 1;
			this.ALL.AutoSize = true;
			this.ALL.Checked = global::WindowsApplication1.My.MySettings.Default.ALLQTY;
			this.ALL.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "ALLQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control all = this.ALL;
			location = new global::System.Drawing.Point(362, 354);
			all.Location = location;
			this.ALL.Name = "ALL";
			global::System.Windows.Forms.Control all2 = this.ALL;
			size = new global::System.Drawing.Size(72, 16);
			all2.Size = size;
			this.ALL.TabIndex = 0;
			this.ALL.Text = "所有功能";
			this.ToolTip1.SetToolTip(this.ALL, "所有功能");
			this.ALL.UseVisualStyleBackColor = true;
			this.COPQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "COPQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.COPQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.COPQTY;
			global::System.Windows.Forms.Control copqty = this.COPQTY;
			location = new global::System.Drawing.Point(170, 57);
			copqty.Location = location;
			this.COPQTY.MaxLength = 2;
			this.COPQTY.Name = "COPQTY";
			global::System.Windows.Forms.Control copqty2 = this.COPQTY;
			size = new global::System.Drawing.Size(41, 21);
			copqty2.Size = size;
			this.COPQTY.TabIndex = 1;
			this.ZCS.AutoSize = true;
			this.ZCS.Checked = global::WindowsApplication1.My.MySettings.Default.ZCSQTY;
			this.ZCS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "ZCSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control zcs = this.ZCS;
			location = new global::System.Drawing.Point(218, 354);
			zcs.Location = location;
			this.ZCS.Name = "ZCS";
			global::System.Windows.Forms.Control zcs2 = this.ZCS;
			size = new global::System.Drawing.Size(48, 16);
			zcs2.Size = size;
			this.ZCS.TabIndex = 0;
			this.ZCS.Text = "资产";
			this.ToolTip1.SetToolTip(this.ZCS, "ZCS 资产");
			this.ZCS.UseVisualStyleBackColor = true;
			this.SXM.AutoSize = true;
			this.SXM.Checked = global::WindowsApplication1.My.MySettings.Default.SXMQTY;
			this.SXM.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "SXMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control sxm = this.SXM;
			location = new global::System.Drawing.Point(218, 290);
			sxm.Location = location;
			this.SXM.Name = "SXM";
			global::System.Windows.Forms.Control sxm2 = this.SXM;
			size = new global::System.Drawing.Size(72, 16);
			sxm2.Size = size;
			this.SXM.TabIndex = 0;
			this.SXM.Text = "物料需求";
			this.ToolTip1.SetToolTip(this.SXM, "SXM 物料需求");
			this.SXM.UseVisualStyleBackColor = true;
			this.RGS.AutoSize = true;
			this.RGS.Checked = global::WindowsApplication1.My.MySettings.Default.RGSQTY;
			this.RGS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "RGSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control rgs = this.RGS;
			location = new global::System.Drawing.Point(218, 233);
			rgs.Location = location;
			this.RGS.Name = "RGS";
			global::System.Windows.Forms.Control rgs2 = this.RGS;
			size = new global::System.Drawing.Size(72, 16);
			rgs2.Size = size;
			this.RGS.TabIndex = 0;
			this.RGS.Text = "报表生成";
			this.ToolTip1.SetToolTip(this.RGS, "RGS 报表生成");
			this.RGS.UseVisualStyleBackColor = true;
			this.KJS.AutoSize = true;
			this.KJS.Checked = global::WindowsApplication1.My.MySettings.Default.KJSQTY;
			this.KJS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "KJSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control kjs = this.KJS;
			location = new global::System.Drawing.Point(218, 172);
			kjs.Location = location;
			this.KJS.Name = "KJS";
			global::System.Windows.Forms.Control kjs2 = this.KJS;
			size = new global::System.Drawing.Size(72, 16);
			kjs2.Size = size;
			this.KJS.TabIndex = 0;
			this.KJS.Text = "会计总账";
			this.ToolTip1.SetToolTip(this.KJS, "KJS 会计总账");
			this.KJS.UseVisualStyleBackColor = true;
			this.GYS.AutoSize = true;
			this.GYS.Checked = global::WindowsApplication1.My.MySettings.Default.GYSQTY;
			this.GYS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "GYSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control gys = this.GYS;
			location = new global::System.Drawing.Point(218, 114);
			gys.Location = location;
			this.GYS.Name = "GYS";
			global::System.Windows.Forms.Control gys2 = this.GYS;
			size = new global::System.Drawing.Size(72, 16);
			gys2.Size = size;
			this.GYS.TabIndex = 0;
			this.GYS.Text = "工单工艺";
			this.ToolTip1.SetToolTip(this.GYS, "GYS 工单工艺");
			this.GYS.UseVisualStyleBackColor = true;
			this.COP.AutoSize = true;
			this.COP.Checked = global::WindowsApplication1.My.MySettings.Default.COPQTY;
			this.COP.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "COPQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control cop = this.COP;
			location = new global::System.Drawing.Point(218, 59);
			cop.Location = location;
			this.COP.Name = "COP";
			global::System.Windows.Forms.Control cop2 = this.COP;
			size = new global::System.Drawing.Size(48, 16);
			cop2.Size = size;
			this.COP.TabIndex = 0;
			this.COP.Text = "销售";
			this.ToolTip1.SetToolTip(this.COP, "COP 销售");
			this.COP.UseVisualStyleBackColor = true;
			this.YSFQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "YSFQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.YSFQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.YSFQTY;
			global::System.Windows.Forms.Control ysfqty = this.YSFQTY;
			location = new global::System.Drawing.Point(23, 350);
			ysfqty.Location = location;
			this.YSFQTY.MaxLength = 2;
			this.YSFQTY.Name = "YSFQTY";
			global::System.Windows.Forms.Control ysfqty2 = this.YSFQTY;
			size = new global::System.Drawing.Size(41, 21);
			ysfqty2.Size = size;
			this.YSFQTY.TabIndex = 1;
			this.YSF.AutoSize = true;
			this.YSF.Checked = global::WindowsApplication1.My.MySettings.Default.YSFQTY;
			this.YSF.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "YSFQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control ysf = this.YSF;
			location = new global::System.Drawing.Point(70, 350);
			ysf.Location = location;
			this.YSF.Name = "YSF";
			global::System.Windows.Forms.Control ysf2 = this.YSF;
			size = new global::System.Drawing.Size(72, 16);
			ysf2.Size = size;
			this.YSF.TabIndex = 0;
			this.YSF.Text = "应收应付";
			this.ToolTip1.SetToolTip(this.YSF, "YSF 应收应付");
			this.YSF.UseVisualStyleBackColor = true;
			this.SGMQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "SGMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.SGMQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.SGMQTY;
			global::System.Windows.Forms.Control sgmqty = this.SGMQTY;
			location = new global::System.Drawing.Point(23, 286);
			sgmqty.Location = location;
			this.SGMQTY.MaxLength = 2;
			this.SGMQTY.Name = "SGMQTY";
			global::System.Windows.Forms.Control sgmqty2 = this.SGMQTY;
			size = new global::System.Drawing.Size(41, 21);
			sgmqty2.Size = size;
			this.SGMQTY.TabIndex = 1;
			this.SGM.AutoSize = true;
			this.SGM.Checked = global::WindowsApplication1.My.MySettings.Default.SGMQTY;
			this.SGM.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "SGMQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control sgm = this.SGM;
			location = new global::System.Drawing.Point(70, 286);
			sgm.Location = location;
			this.SGM.Name = "SGM";
			global::System.Windows.Forms.Control sgm2 = this.SGM;
			size = new global::System.Drawing.Size(72, 16);
			sgm2.Size = size;
			this.SGM.TabIndex = 0;
			this.SGM.Text = "生产管理";
			this.ToolTip1.SetToolTip(this.SGM, "SGM 生产管理");
			this.SGM.UseVisualStyleBackColor = true;
			this.QMSQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "QMSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.QMSQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.QMSQTY;
			global::System.Windows.Forms.Control qmsqty = this.QMSQTY;
			location = new global::System.Drawing.Point(23, 229);
			qmsqty.Location = location;
			this.QMSQTY.MaxLength = 2;
			this.QMSQTY.Name = "QMSQTY";
			global::System.Windows.Forms.Control qmsqty2 = this.QMSQTY;
			size = new global::System.Drawing.Size(41, 21);
			qmsqty2.Size = size;
			this.QMSQTY.TabIndex = 1;
			this.QMS.AutoSize = true;
			this.QMS.Checked = global::WindowsApplication1.My.MySettings.Default.QMSQTY;
			this.QMS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "QMSQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control qms = this.QMS;
			location = new global::System.Drawing.Point(70, 229);
			qms.Location = location;
			this.QMS.Name = "QMS";
			global::System.Windows.Forms.Control qms2 = this.QMS;
			size = new global::System.Drawing.Size(72, 16);
			qms2.Size = size;
			this.QMS.TabIndex = 0;
			this.QMS.Text = "检验管理";
			this.ToolTip1.SetToolTip(this.QMS, "QMS 检验管理");
			this.QMS.UseVisualStyleBackColor = true;
			this.JCAQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "JCAQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.JCAQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.JCAQTY;
			global::System.Windows.Forms.Control jcaqty = this.JCAQTY;
			location = new global::System.Drawing.Point(23, 168);
			jcaqty.Location = location;
			this.JCAQTY.MaxLength = 2;
			this.JCAQTY.Name = "JCAQTY";
			global::System.Windows.Forms.Control jcaqty2 = this.JCAQTY;
			size = new global::System.Drawing.Size(41, 21);
			jcaqty2.Size = size;
			this.JCAQTY.TabIndex = 1;
			this.JCA.AutoSize = true;
			this.JCA.Checked = global::WindowsApplication1.My.MySettings.Default.JCAQTY;
			this.JCA.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "JCAQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control jca = this.JCA;
			location = new global::System.Drawing.Point(70, 168);
			jca.Location = location;
			this.JCA.Name = "JCA";
			global::System.Windows.Forms.Control jca2 = this.JCA;
			size = new global::System.Drawing.Size(72, 16);
			jca2.Size = size;
			this.JCA.TabIndex = 0;
			this.JCA.Text = "营业决策";
			this.ToolTip1.SetToolTip(this.JCA, "JCA 营业决策");
			this.JCA.UseVisualStyleBackColor = true;
			this.FIBQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "FIBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.FIBQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.FIBQTY;
			global::System.Windows.Forms.Control fibqty = this.FIBQTY;
			location = new global::System.Drawing.Point(23, 110);
			fibqty.Location = location;
			this.FIBQTY.MaxLength = 2;
			this.FIBQTY.Name = "FIBQTY";
			global::System.Windows.Forms.Control fibqty2 = this.FIBQTY;
			size = new global::System.Drawing.Size(41, 21);
			fibqty2.Size = size;
			this.FIBQTY.TabIndex = 1;
			this.FIB.AutoSize = true;
			this.FIB.Checked = global::WindowsApplication1.My.MySettings.Default.FIBQTY;
			this.FIB.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "FIBQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control fib = this.FIB;
			location = new global::System.Drawing.Point(70, 110);
			fib.Location = location;
			this.FIB.Name = "FIB";
			global::System.Windows.Forms.Control fib2 = this.FIB;
			size = new global::System.Drawing.Size(60, 16);
			fib2.Size = size;
			this.FIB.TabIndex = 0;
			this.FIB.Text = "财务包";
			this.ToolTip1.SetToolTip(this.FIB, "FIB 财务包(会计总帐/应收应付)");
			this.FIB.UseVisualStyleBackColor = true;
			this.BASQTY.DataBindings.Add(new global::System.Windows.Forms.Binding("Enabled", global::WindowsApplication1.My.MySettings.Default, "BASQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			this.BASQTY.Enabled = global::WindowsApplication1.My.MySettings.Default.BASQTY;
			global::System.Windows.Forms.Control basqty = this.BASQTY;
			location = new global::System.Drawing.Point(23, 55);
			basqty.Location = location;
			this.BASQTY.MaxLength = 2;
			this.BASQTY.Name = "BASQTY";
			global::System.Windows.Forms.Control basqty2 = this.BASQTY;
			size = new global::System.Drawing.Size(41, 21);
			basqty2.Size = size;
			this.BASQTY.TabIndex = 1;
			this.BAS.AutoSize = true;
			this.BAS.Checked = global::WindowsApplication1.My.MySettings.Default.BASQTY;
			this.BAS.DataBindings.Add(new global::System.Windows.Forms.Binding("Checked", global::WindowsApplication1.My.MySettings.Default, "BASQTY", true, global::System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
			global::System.Windows.Forms.Control bas = this.BAS;
			location = new global::System.Drawing.Point(70, 55);
			bas.Location = location;
			this.BAS.Name = "BAS";
			global::System.Windows.Forms.Control bas2 = this.BAS;
			size = new global::System.Drawing.Size(60, 16);
			bas2.Size = size;
			this.BAS.TabIndex = 0;
			this.BAS.Text = "基础包";
			this.ToolTip1.SetToolTip(this.BAS, "BAS 基础包（销售/采购/存货/应收应付/报表生成）");
			this.BAS.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control regstr = this.REGSTR;
			location = new global::System.Drawing.Point(13, 488);
			regstr.Location = location;
			this.REGSTR.Name = "REGSTR";
			global::System.Windows.Forms.Control regstr2 = this.REGSTR;
			size = new global::System.Drawing.Size(618, 21);
			regstr2.Size = size;
			this.REGSTR.TabIndex = 3;
			this.ToolTip1.SetToolTip(this.REGSTR, "请输入要注册的公司名！");
			this.Label61.AutoSize = true;
			global::System.Windows.Forms.Control label113 = this.Label61;
			location = new global::System.Drawing.Point(12, 470);
			label113.Location = location;
			this.Label61.Name = "Label61";
			global::System.Windows.Forms.Control label114 = this.Label61;
			size = new global::System.Drawing.Size(65, 12);
			label114.Size = size;
			this.Label61.TabIndex = 2;
			this.Label61.Text = "注册公司名";
			this.Label62.AutoSize = true;
			global::System.Windows.Forms.Control label115 = this.Label62;
			location = new global::System.Drawing.Point(10, 520);
			label115.Location = location;
			this.Label62.Name = "Label62";
			global::System.Windows.Forms.Control label116 = this.Label62;
			size = new global::System.Drawing.Size(41, 12);
			label116.Size = size;
			this.Label62.TabIndex = 2;
			this.Label62.Text = "序列号";
			global::System.Windows.Forms.Control pw = this.PW;
			location = new global::System.Drawing.Point(496, 538);
			pw.Location = location;
			this.PW.Name = "PW";
			this.PW.ReadOnly = true;
			global::System.Windows.Forms.Control pw2 = this.PW;
			size = new global::System.Drawing.Size(135, 21);
			pw2.Size = size;
			this.PW.TabIndex = 1;
			this.Label63.AutoSize = true;
			global::System.Windows.Forms.Control label117 = this.Label63;
			location = new global::System.Drawing.Point(494, 520);
			label117.Location = location;
			this.Label63.Name = "Label63";
			global::System.Windows.Forms.Control label118 = this.Label63;
			size = new global::System.Drawing.Size(53, 12);
			label118.Size = size;
			this.Label63.TabIndex = 2;
			this.Label63.Text = "验证口令";
			this.Label64.AutoSize = true;
			global::System.Windows.Forms.Control label119 = this.Label64;
			location = new global::System.Drawing.Point(12, 7);
			label119.Location = location;
			this.Label64.Name = "Label64";
			global::System.Windows.Forms.Control label120 = this.Label64;
			size = new global::System.Drawing.Size(53, 12);
			label120.Size = size;
			this.Label64.TabIndex = 2;
			this.Label64.Text = "安装代号";
			this.ToolTip1.IsBalloon = true;
			global::System.Windows.Forms.Control ccode = this.CCode;
			location = new global::System.Drawing.Point(478, 24);
			ccode.Location = location;
			this.CCode.MaxLength = 6;
			this.CCode.Name = "CCode";
			global::System.Windows.Forms.Control ccode2 = this.CCode;
			size = new global::System.Drawing.Size(153, 21);
			ccode2.Size = size;
			this.CCode.TabIndex = 1;
			this.ToolTip1.SetToolTip(this.CCode, "请输入客服代号！");
			this.Label55.AutoSize = true;
			global::System.Windows.Forms.Control label121 = this.Label55;
			location = new global::System.Drawing.Point(476, 7);
			label121.Location = location;
			this.Label55.Name = "Label55";
			global::System.Windows.Forms.Control label122 = this.Label55;
			size = new global::System.Drawing.Size(53, 12);
			label122.Size = size;
			this.Label55.TabIndex = 2;
			this.Label55.Text = "客户代号";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleDimensions = autoScaleDimensions;
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(643, 610);
			base.ClientSize = size;
			base.Controls.Add(this.REGSTR);
			base.Controls.Add(this.GroupBox1);
			base.Controls.Add(this.PW);
			base.Controls.Add(this.KEY);
			base.Controls.Add(this.CCode);
			base.Controls.Add(this.SN);
			base.Controls.Add(this.Label55);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.Label64);
			base.Controls.Add(this.Label63);
			base.Controls.Add(this.Label62);
			base.Controls.Add(this.Label61);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.Name = "Form1";
			this.Text = "Keygen";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000009 RID: 9
		private global::System.ComponentModel.IContainer components;
	}
}
